[package]
name = "impl-converter-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warned = { version = "0.1", optional = true }

[dev-dependencies]
anyhow = "1.0"
